# This playbook consists of four plays. The first one pulls information about all the default rho facts and the second
# writes them to a csv with the name specified. The third one pulls information about only those facts we intend to
# collect (as demonstrated in the example) and the fourth one writes them to a file as specified.

---

- name: collect all requested facts
  hosts: all
  roles:
    - connection
    - cpu
    - date
    - dmi
    - etc_release
    - file_contents
    - redhat_release
    - redhat_packages
    - subman
    - uname
    - virt
    - virt_what
    - jboss
    - brms
    - fuse


- name: write facts first to a variable and then to csv locally
  hosts: localhost
  roles:
    - write
